import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <nav className="flex items-center justify-center border-b border-gray-300">
            <Link href="/" className="px-4 py-2 hover:bg-gray-200">Home</Link>
            <Link href="/task" className="px-4 py-2 hover:bg-gray-200">Task</Link>
          </nav>
          <hr />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
